.TH LIB-SECRET-MANAGER 1 "2026-08-10" "1.0.0" "Lib-Secret Manager"
.SH NAME
lib-secret-manager \- password manager for Linux via libsecret
.SH SYNOPSIS
.B lib-secret-manager
.SH DESCRIPTION
Lib-Secret Manager is a simple and secure password manager for Linux.
It allows you to manage secrets stored in the system keyring via libsecret.
.SH OPTIONS
No command-line options.
.SH FILES
.TP
.I /usr/bin/lib-secret-manager
Executable
.TP
.I /usr/share/applications/lib-secret-manager.desktop
Desktop entry
.SH AUTHOR
Dmitry Kh <admin@linuxaiworks.ru>
.SH HOMEPAGE
https://github.com/linuxaiworks/lib-secret-manager