#!/bin/sh
set -e

case "$1" in
    configure)
        if [ -x /usr/bin/update-desktop-database ]; then
            update-desktop-database /usr/share/applications >/dev/null 2>&1 || true
        fi
        if [ -x /usr/bin/gtk-update-icon-cache ]; then
            gtk-update-icon-cache -f /usr/share/icons/hicolor >/dev/null 2>&1 || true
        fi
        if [ -x /usr/bin/update-icon-caches ]; then
            update-icon-caches /usr/share/icons/hicolor >/dev/null 2>&1 || true
        fi
        ;;
esac

#DEBHELPER#

exit 0